# Generated by Django 2.2.7 on 2019-11-29 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Statuses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='SiteStatuses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructorapi.Sites')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructorapi.Statuses')),
            ],
        ),
        migrations.CreateModel(
            name='Mains',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructorapi.Sites')),
            ],
        ),
        migrations.CreateModel(
            name='HtmlHeads',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bode', models.TextField()),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructorapi.Sites')),
            ],
        ),
        migrations.CreateModel(
            name='Headers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructorapi.Sites')),
            ],
        ),
        migrations.CreateModel(
            name='Footers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructorapi.Sites')),
            ],
        ),
        migrations.CreateModel(
            name='BlockTemplates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructorapi.Sites')),
            ],
        ),
        migrations.CreateModel(
            name='AddedBlocks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructorapi.Sites')),
            ],
        ),
    ]
